[secrets]
SUPABASE_PROJECT_REF = { description = "Full URL for Supabase MCP server" }
SUPABASE_URL = { description = "Supabase access url" }
SUPABASE_ANON_KEY = { description = "Anon key to access Supabase" }
TMDB_API_KEY = { description = "TMDB API key to access TMDB database" }
